# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3eecb0d726462b8466d46acf466e06bf8e0a470cd9df1cc4981912298f09ee26077d4bea1ea3eb2e4519c7c251ddcafb8474c99f8a6905c36ec280e6fd654984

test:
  secret_key_base: d866f43fcfd7ef5f4612b66fd73e9157b03d083dfaa24b74268e924b2620eb7fc4905fc88a72714691edbf0f2231f0996433541968389f8d6ee4a7c528fdd0e5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
